### ISSUE TITLE
Handle "skipped" packages

### ISSUE THREAD

**Issue by yan12125** [a-wing/KISS2U#11]
For example, in https://build.archlinuxcn.org/packages/#/rust-nightly, the build at 2019/6/10 上午11:04:32 is marked as failed. It's actually skipped. From `build.archlinuxcn.org:/home/lilydjwg/.lilac/build.log`:
```
[2019-06-10 11:04:32] rust-nightly 1.37.0-nightly (400b409ef 2019-06-09) skipped after 1s
```

**Comment by a-wing** [comment]
Added https://github.com/a-wing/KISS2UI/commit/290b3b897d641f1ea33530a9857ce5b7c5735e14#diff-3dc7d774bf0e0fc2a816d296193804dcR24

**Comment by yan12125** [comment]
Cool, thanks!
