### ISSUE TITLE
Feature Request: More filter options

### ISSUE THREAD

**Issue by VOID001** [a-wing/KISS2U#3]
It's really a good project! Now I can know when lilac build my package and get the result, build time ASAP.
Do you think it would be better if more filter options are supported? For example filter by maintainer(packager, etc). Then I can view all the package status maintained by me :smile:

**Comment by a-wing** [comment]
The first of all. I need get maintainer => package . but nvcheck.ini have maybe plan use SQLite3.......

I wait for after `nvchecker.ini` upgrade add `maintainer => package`

**Comment by VOID001** [comment]
Cool, SQLite will be better for structured data

**Comment by a-wing** [comment]
Search by user Added https://github.com/a-wing/KISS2UI/commit/e6a160bedbe76e70a8122a4ca166737e2ccb617d
