### ISSUE TITLE
all contents can be compressed by gzip or others

### ISSUE THREAD

**Issue by Sherlock-Holo** [a-wing/KISS2U#4]
- `build.js` 968KB
- `https://build.archlinuxcn.org/api/packages/` 90.5KB

I suppose you can compress those to boost the load speed

**Comment by a-wing** [comment]
Build.js also has optimized space

gzip: Web server Configuration

**Comment by lilydjwg** [comment]
nginx 的 gzip 已开。

**Comment by a-wing** [comment]
https://github.com/a-wing/KISS2UI/commit/ed9f35b5213a74974e261a45623dd9126583d5cb

`build.js` 968k => 460k
