### ISSUE TITLE
Pkgver is not correct

### ISSUE THREAD

**Issue by Xuanwo** [a-wing/KISS2U#6]
For example:

![image](https://user-images.githubusercontent.com/5351546/47099747-8b484080-d268-11e8-8808-2c42b6b01b46.png)

`zsh-syntax-highlighting-git` 's pkgver shoule be `0.6.0.r184.g47c2b7e` instead of `20181013.143709`

**Comment by a-wing** [comment]
![image](https://user-images.githubusercontent.com/18189138/47126225-23bae100-d2ba-11e8-8d46-1d0906956974.png)

lilac build.log `zsh-syntax-highlighting-git` 's pkgver `20181013.143709`



cc @lilydjwg

**Comment by lilydjwg** [comment]
I'll include built pkgver in the log when I have time.

**Comment by lilydjwg** [comment]
Added pkgver & pkgrel info in the log.

**Comment by a-wing** [comment]
![image](https://user-images.githubusercontent.com/18189138/47211818-19d3d380-d3c9-11e8-8cf2-6b28bc076ed0.png)

:thinking: The pkgver need cut date ?

`64.0a1 19-Oct-2018 02:41 [64.0a1.20181019.02-1]` is pkgver ?

**Comment by lilydjwg** [comment]
The text in brackets is pkgver + pkgrel.
