### ISSUE TITLE
Pkgver for linux-macbook is broken

### ISSUE THREAD

**Issue by Xuanwo** [a-wing/KISS2U#7]
It should be `4.18.16-arch1`, but `KISS2U` shows `${_srcver//-/.}-1`

ref: https://build.archlinuxcn.org/packages/#/linux-macbook

**Comment by a-wing** [comment]
kiss2u read message for lilac/build.log

cc @lilydjwg
```
$ tail -100 /home/lilydjwg/.lilac/build.log |grep linux-macbook              
[2018-10-28 09:47:15] linux-macbook 4.18.16.arch1-1 [${_srcver//-/.}-1] successful after 1235s
```

**Comment by lilydjwg** [comment]
Oops...Need a better way.

**Comment by lilydjwg** [comment]
这个可以和 https://github.com/archlinuxcn/lilac/issues/84 一起处理，从 srcinfo 中读取。

**Comment by lilydjwg** [comment]
已经处理了。
