### ISSUE TITLE
Pacakge pcl is not managed by lilac, but still appear on KISS2UI

### ISSUE THREAD

**Issue by VOID001** [a-wing/KISS2U#9]
![image](https://user-images.githubusercontent.com/6134883/50531890-f6a56d00-0b4b-11e9-8ca8-a3d1cbf6de7c.png)
But https://github.com/archlinuxcn/repo/tree/master/pcl/ doesn't contain lilac.py / lilac.yaml file
Could you please explain why this happens?

**Comment by VOID001** [comment]
I found that the package is previously managed by lilac. But now the package pass the build manually.

**Comment by a-wing** [comment]
```
$ tail -10000 /home/lilydjwg/.lilac/build.log |grep pcl
[2018-09-23 03:37:25] pcl 1.8.1-7 failed after 11s
[2018-09-26 04:15:21] pcl 1.8.1-8 failed after 9s
```

no problem (

Build manually, Currently KISS2U not get log
